# Generated by Django 3.1.7 on 2021-05-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_auto_20210516_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
