# Generated by Django 3.1.7 on 2021-05-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_auto_20210516_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products_list',
            field=models.TextField(default=''),
        ),
    ]
