# Generated by Django 3.1.7 on 2021-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0010_auto_20210516_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
