# Generated by Django 3.1.7 on 2021-05-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0012_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
