# Generated by Django 3.1.7 on 2021-05-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0013_remove_cart_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='cantitate',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='pret',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='produs',
        ),
    ]
