# Generated by Django 3.1.7 on 2021-05-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0015_auto_20210519_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='cantitate',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='pret',
        ),
    ]
