# Generated by Django 3.1.7 on 2021-05-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0020_auto_20210519_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cantitate',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='produs',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='pret',
            new_name='quantity',
        ),
    ]
