# Generated by Django 3.1.7 on 2021-05-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
