# Generated by Django 3.1.7 on 2021-05-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_slug',
            new_name='slug',
        ),
    ]
