# Generated by Django 3.1.7 on 2021-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
