# Generated by Django 3.1.7 on 2021-05-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_product_p_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
