# Generated by Django 3.1.7 on 2021-05-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_price',
            new_name='price',
        ),
    ]
