# Generated by Django 3.1.7 on 2021-05-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20210517_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='empty.jpg', upload_to='products/%d/'),
        ),
    ]
