# Generated by Django 3.1.7 on 2021-05-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='an_fabricatie',
            field=models.PositiveIntegerField(default=2001),
        ),
        migrations.AddField(
            model_name='product',
            name='capacitate_cilindrica',
            field=models.PositiveIntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='product',
            name='caroserie',
            field=models.CharField(default='Sedan', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='culoare',
            field=models.CharField(default='Rosu', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='data_primei_inmatriculari',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kilometraj',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='product',
            name='motorizare',
            field=models.CharField(default='Diesel', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='norma_de_poluare',
            field=models.CharField(default='Euro 6', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='numar_portiere',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='product',
            name='putere',
            field=models.PositiveIntegerField(default=101),
        ),
        migrations.AddField(
            model_name='product',
            name='stare',
            field=models.CharField(default='Second hand', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='tara_de_origine',
            field=models.CharField(default='Germania', max_length=25),
        ),
    ]
