# Generated by Django 3.1.7 on 2021-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20210518_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oferit_de',
            field=models.CharField(default='Persoana fizica', max_length=25),
        ),
    ]
