# Generated by Django 3.1.7 on 2021-05-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_product_oferit_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serie_sasiu',
            field=models.CharField(default='', max_length=30),
        ),
    ]
