# Generated by Django 3.1.7 on 2021-05-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_product_serie_sasiu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serie_sasiu',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
